### ISSUE TITLE
Crashes once run

### ISSUE THREAD

**Issue by PavanLuca** [Der1248/Agon#2]
I tried all world types and any loaded just says this:

`ModError: Failed to load and run script from /home/luca/.var/app/net.minetest.Minetest/.minetest/games/agon/mods/doors/init.lua: /app/share/minetest/builtin/game/register.lua:199: bad argument #5 to 'register_item_raw' (table expected, got string) stack traceback: [C]: in function 'register_item_raw' /app/share/minetest/builtin/game/register.lua:199: in function 'register_item' /app/share/minetest/builtin/game/register.lua:225: in function 'register_node' ...netest.Minetest/.minetest/games/agon/mods/doors/init.lua:796: in function 'register_fencegate' ...netest.Minetest/.minetest/games/agon/mods/doors/init.lua:808: in main chunk`

Doors are a bad person 😡️.

**Comment by Der1248** [comment]
Agon was not previously designed for the newer Minetest versions. I removed all unnecessary mods. Should be fixed with version 3.0.6
